version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8080"
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
