services:
  backend:
    build: ./backend
    expose:
      - "8080"
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
